# Generated by Django 5.1.3 on 2024-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trf_core', '0002_barcode_assigned_at_barcode_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
